---
title: "Data Visualisation Question04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

# set working directory, either manually or by 'setwd()' command

# load packages
```{r }
library(palmerpenguins)
library(ggplot2)
suppressPackageStartupMessages(library(janitor))
suppressPackageStartupMessages(library(dplyr))
library(tidyr)
library(svglite)

#alternatively, can load the packages from a pre-saved r script 
#in format:
#source(libraries.r, "functions/ libraries.r")
```

**FUNCTIONS**
# load functions
```{r }
cleaning <- function(data_raw){
  data_raw %>%
    clean_names() %>%
    remove_empty(c("rows", "cols")) %>%
    select(-starts_with("delta")) %>%
    select(-comments)
}

# Function filters for penguins only on Biscoe Island and removes any NA in bodymass
AxG_massXclength <- function(data_clean){
  data_clean %>%
    filter(!is.na(body_mass_g), island == "Biscoe") %>%
    select(species, body_mass_g, culmen_length_mm)
}
#Similarly, as before coulld also
#source(cleaning.r, "functions/cleaning.r")
```

# load functions - plotting
```{r }
plot_AG_MxCL_fig <- function(AG_MxCL){
  AG_MxCL %>% 
    ggplot( aes(x = body_mass_g, y = culmen_length_mm)) +
    ggtitle("The relationship between body mass and culmen length of penguins on Biscoe Island") +
        geom_smooth(method = "lm" ) +
    geom_point(aes(color = species) , alpha = 0.4, show.legend = TRUE) +
    scale_color_manual(values = c("orange","purple")) +
    labs(x = "Body mass (g)", 
        y = "Culmen length (mm)") +
    theme_bw()
}
#Alternatively
#source(plotting.r, "functions/plotting.r")
```

# load function - saving a svg. => as a vector so can be zoomed into without becoming blurry
```{r }
save_AG_MxCL_plot_svg <- function(AG_MxCL, filename, size, scaling){
  size_inches = size/2.54
  svglite(filename, width = size_inches, height = size_inches, scaling = scaling)
  AG_MxCL_plot <- plot_AG_MxCL_fig(AG_MxCL)
  print(massXclength_plot)
  dev.off()
}
#Alternatively
##source(saving.r, "functions/saving.r")
```


**RUNNING CODE**
```{r }
# Loading the raw penguin data & save 
write.csv(penguins_raw, "data_raw/penguins_raw.csv")
penguins_raw <- read.csv("data_raw/penguins_raw.csv")
```


```{r }
# clean it & save a copy
penguins_clean <- cleaning(penguins_raw) 
write.csv(penguins_clean, "data_clean/penguins_clean.csv")
```


```{r }
# filter it - subset data we want to look at
AG_MxCL <- AxG_massXclength(penguins_clean)
```


```{r }
#plot
AG_MxCL_plot <- plot_AG_MxCL_fig(AG_MxCL)
AG_MxCL_plot

```


```{r }
#Conduct a statistical test - ANOVA

lm_AG_MxCL <- lm(body_mass_g ~ culmen_length_mm, AG_MxCL) #creates a linear model
anova(lm_AG_MxCL) # carry out the ANOVA test; work out significance based on P value and F value

```

```{r }
#save as a svg.
save_AG_MxCL_plot_svg(AG_MxCL_plot, "figures/AG_MxCL_vector.svg", 
                           size = 15, scaling = 1)

```

```{r }


```

```{r }


```

